### PR TITLE
Add watchdog to stop robot if no cmd_vel received

### PR DESCRIPTION
**Pull request by mintar**
Without this commit, the robot simply continues driving at the speed from the last received `cmd_vel` message, even if the node that is supposed to send the `cmd_vel` messages crashes. It is standard behavior in ROS for robots to stop in this case (at least that's what the PR2 and every other robot I have worked with so far does).

### CODE REVIEW

**Comment by mintar** [comment]
Incidentally, this bug has led our robot to collide with a five-figure piece of equipment. Nothing was damaged though. :)

**Comment by reed-adept** [comment]
Can we make the timeout configurable (and optional, just ignore if parameter is 0 or something should be ok)?

**Comment by reed-adept** [comment]
Also an alternative is to disable ARIA's behavior of continuing to send commands on its regular cycle, so they are only sent when cmd_vel is received by ROSARIA, which will then rely on the robot controller (firmware) to timeout.  But this way is simple and easy so no reason not to add it  I  think?

**Comment by progtologist** [comment]
I would also prefer the timeout to be user configurable, other than that, seems great and necessary!

**Comment by mintar** [comment]
Thanks for the feedback! I've updated my pull request. The timeout is now configurable via the parameter `~cmd_vel_timeout` and only enabled if the parameter is >= 0.

**Comment by reed-adept** [comment]
OK merged it, everyone please test and report any problems.  Thanks for the contribution!

By the way I looked into disabling ARIA's behavior of caching and continuing to send the velocity to the actual robot controller in its "state reflection" cycle.  At one point in the distant past there was a flag to supposedly disable this, but it was removed at some point.  So the alternative would be for rosaria to use `com(ArCommands::VEL, vel);` instead of the `setVel(vel)` function, i.e. bypass ArRobot entirely with the command.  Maybe I'll consider adding more official facility to do this in ARIA at some point, or if we ever want rosaria to do this someday, it is still possible to modify it in all places where `setVel()`, `setRotVel()`, accelerations are currently used, but it would be a bit of an intrusive or cumbersome change.

**Pull request merged**
