### PR TITLE
Add covariance for published odometry

### PR DESCRIPTION
**Pull request by lakid**
The node is modified to publish empirical Covariance that change according to if the robot is stationary or moving.

### CODE REVIEW

**Comment by lakid** [comment]
Sorry I issued this pull request for the local repository. Somehow git hub decided to issue it to the global repo.

**Comment by reed-adept** [comment]
No problem, but you can reopen this pull request so we can consider adding this at some point.  Or open an issue (bug) report for it.    What robot did you use to empirically test for the covariance?  What do you think the best way to provide covariance for different robots is?   What procedure did you use to test for the covariance, is there a document somewhere about this or should we create one?

Thanks

Reed

**Comment by lakid** [comment]
Sorry for the late reply. Well currently the update consists of 2 covariance states, while running where you get a high value for the variance terms. The other one is while standing still where the robot is more confident about its x/y location not changing.

The primary reason for the update is to use the encoder odometry in an EKF framework.

Furthermore the master branch of the public fork `TRECVT/rosaria` now publishes Sick S3 laser data into ROS space as a `sensor\_msg::LaserScan`. This update is only for the _Pioneer LX_ which comes with an inbuilt LRF. 

Most values for publishing the scan is currently obtained from the datasheet rather than through the driver itself(I believe this is possible). This was produced as a quick hack for a last minute requirement and therefore needs to be properly updated.

**Comment by reed-adept** [comment]
So the covariance was based on observing the Pioneer LX?  Ok, we’ll try to come up with a good way to do this for all robots, so any ideas you have would be great.

I will eventually integrate laser publishing, I’ll probably start with your changes as a basis and make sure it works for other laser types and take laser position and other info from robot parameters.

**Pull request closed without merging**
